- deps/build.jl
This is where my `libjulia.so` exits after making julia0.4 from source.
> add "julia/usr/lib" path to check for libjulia.so

- deps/build.jl
Fixes needed to get this package to compile when running julia 0.4 directly from its build directory in Linux.
> Build path fix for running from build in linux

- src/CxxWrap.jl
Not needed since 0.4 and above support __precompile__
> remove isdefined __precompile__

- REQUIRE
only need parametric type aliases, not anything newer at the moment
ref https://github.com/JuliaLang/METADATA.jl/pull/8818#discussion_r111274943
> lower Compat requirement to 0.18

- REQUIRE
- src/CxxWrap.jl
from Compat 0.19 - otherwise the package will be broken on early 0.6-dev versions
from before this renaming
hadn't noticed this in the diff yet
> Use at-compat for IndexStyle

- deps/src/cxx_wrap/include/cxx_wrap/cxx_wrap.hpp
Prevents copies of the functor.
> add_lambda move semantics

- deps/src/cxx_wrap/include/cxx_wrap/type_conversion.hpp
- src/CxxWrap.jl
Fixex https://github.com/QuantStack/xtensor-julia/pull/46 with respect to non fully specialized parametric types not being data type anymore with Julia 0.6, but unionall instead.
cf. https://discourse.julialang.org/t/what-is-a-unionall-type/721/3
> DataType -> Type

- deps/src/jlcxx/include/jlcxx/jlcxx.hpp
- deps/src/jlcxx/include/jlcxx/type_conversion.hpp
1) This PR replaces `detail:: JuliaComplex<T>` with `std::complex<T>`.
The only requirement for the `type` typedef in `static_type_mapping` is that it has the same size and provides a meaningful way to use the content, and `std::complex` does that as well as `template <class T> struct { T a; T b; };`.
2) The benefit is in the downstream project `Xtensor.jl` for the handling of arrays of complex numbers.
The jlarray / jltensor are based on a structure called `xbuffer_adaptor` which is a wrapper on a raw buffer providing a `std::vector`-style API, and the wrapping xtensor expression inherit its typedefs from it - and the `xbuffer_adaptor` type is `xbuffer_adaptor<jlcxx::mapped_julia_type<T>>;`... Making this change enables `operator()` to return references on complex numbers in …
> Use std::complex instead of JuliaComplex

- .travis.yml
Allow the test with the Julia nightly build to fail. (Although we would still have the information).
> Allow failure on nighlies

- deps/src/jlcxx/FindJulia.cmake
I've been getting errors of the type
```
CMake Error at /home/jstrube/.julia/v0.6/CxxWrap/deps/usr/share/cmake/JlCxx/FindJulia.cmake:22 (string):
string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
command.
Call Stack (most recent call first):
/home/jstrube/.julia/v0.6/CxxWrap/deps/usr/share/cmake/JlCxx/JlCxxConfig.cmake:2 (find_package)
CMakeLists.txt:13 (find_package)
```
This commit fixes them.
> Adding quotes around variables to string commands

- deps/build.jl
- deps/src/jlcxx/CMakeLists.txt
This changes where the `jlcxxConfig.cmake` gets installed.
The reasons for this are detailed by @ghisvail (Debian package maintainer) in https://github.com/QuantStack/xtensor/pull/349, and we have been updating all the projects since. CxxWrap is one of the upstream project where I used the same pattern for the installation of projectConfig.cmake.
> Project config install directory

- deps/build.jl
This fix only applies to the cases that examples are not required to be built.
> Fixed a minor issue in installing the package (in `build.jl`)

- Manifest.toml
- Project.toml
- REQUIRE
I saw you mention in this commit that the release isn't in the registry yet: https://github.com/JuliaInterop/CxxWrap.jl/pull/136#issuecomment-485110840
In fact, the old "Attobot" way of registering packages has been turned off! See this thread for more information:
https://discourse.julialang.org/t/switching-package-registration-systems-soon/22677/132
------
This PR adds .toml files to this repo so that you can check it in via Registrator.jl! 😄 
I got the `uuid` by checking the General registry here:
https://github.com/JuliaRegistries/General/blob/master/C/CxxWrap/Package.toml
You only actually need the `Project.toml`, but Stefan recommends checking in a Manifest so that people can see an example of a working environment that satisfied the compat requirements and passed the build. Up to …
> Add .toml files to register a version for the new Pkg3 Registry

- src/CxxWrap.jl
- test/build.jl
BinaryProvider is not meant to be loaded at runtime. It does lots of
things that aren't acceptable at runtime, which is why it goes through
the care of generating a `deps.jl` file that doesn't import it.
This commit takes BinaryProvider out of `src/CxxWrap.jl` so that code
using CxxWrap doesn't wind up with BinaryProvider in its runtime
dependencies.
Since it's only used in that one test/build.jl file anyway, this is fine.
> Fix Static Compilation: Move BinaryProvider out of src/, since only used in test/

- README.md
I was getting a `ERROR: LoadError: Type for std::vector<CxxPtr> must be defined in the same module as CxxPtr`, because I didn't follow this rule.
> Add note on template specializations to README

- README.md
The template is no longer needed for enums.
Regarding the name change, I get confused between the name and the type, so I've tried to make them different, but I may well have gotten it wrong.
I've tried to follow the example in your tests/ folder...
I figured that if I got it wrong, you'd let me know. :-)
> Update enum section

- README.md
- src/CxxWrap.jl
The README had some out-of-date links and used an old name for `libcxxwrap-julia`. This PR cleans up the links, and changes the README to one-sentence-per-line. I can revert the latter change if it is unwanted.
> Fix README

- src/CxxWrap.jl
Originally `prefix_path()` will return `""`
> fix `prefix_path`

- test/functions.jl
Explicitly test whether the returned path refers to a valid directory,
and contains the cmake files package rely on.
This is IMHO better than just comparing it to the value it is defined to be,
as this won't catch all kinds of errors; for example if it ever happened that
CxxWrap.CxxWrapCore.libcxxwrap_julia_jll.libcxxwrap_julia_path returns a bogus
value, the old test would still pass
> Improve prefix_path tests

- src/CxxWrap.jl
- test/functions.jl
It would be great if this could be merged and then 0.9.1 be released. Then once 0.10.1 is out with its own fixes for prefix_path, code which wants to be compatible with both 0.9 and 0.10 can write
```julia
jlcxx_cmake_dir = joinpath(CxxWrap.prefix_path(), "lib", "cmake", "JlCxx")
```
instead of monstrosities like this:
```julia
jlcxx_cmake_dir = joinpath(dirname(
isdefined(CxxWrap, :jlcxx_path) && !isempty(CxxWrap.jlcxx_path) ?
CxxWrap.jlcxx_path :
CxxWrap.CxxWrapCore.libcxxwrap_julia_jll.libcxxwrap_julia_path
),"cmake","JlCxx")
```
> Export CxxWrap.prefix_path

- src/CxxWrap.jl
Actually, this is a ruse; in reality I want to see if the regressions we've been encountering since the `libcxxwrap_julia_jll.jl` update also is visible in the CI tests here :-)
> Fix a typo

- README.md
Mention in the README.md documentation the need to include an extra header file to enjoy constant
array functionality.
> Document the need to include const array header.

- README.md
There are some notes in the presentation (I'm thinking specifically the "$(type)Dereferenced" types at  https://barche.github.io/juliacon2020-cxxwrap-talk/#/5/1/2 , but there are othres) that aren't mentioned in the README, so I think it is useful to add a reference to the talk.
I added the reference to the workshop for completeness.
> Reference presentations on CxxWrap

- README.md
Updating references in the README to correctly refer to this as a macro.
> `safe_cfunction` is now a macro.

- Project.toml
- src/CxxWrap.jl
This improves upon PR #282 by making sure it is still safe to store a `SafeCFunction` and uses the proper `cconvert` and `unsafe_convert` mechanism.
> Safecfunction naming

- src/CxxWrap.jl
At the point we issue those ccall, we know that the index is valid.
> Eliminate bounds checks on __cxxwrap_pointers

- README.md
There is no such thing as `std::functor`.  I am pretty sure you mean `std::function`, which is already mentioned elsewhere in the README.
> README: Fix std::functor typo

- src/CxxWrap.jl
- test/types.jl
Leverages tests w.r.t. `IntDerived` since it specifies the `==` function with a method of its own, building upon them by comparing an `IntDerivedDereferenced` object with a `CxxRef{IntDerived}`.  The added test fails without this PR's additional change.
Fixes #250
> Fix `==` ambiguity when overriden for a given type

- .github/workflows/test-prerelease.yml
- .github/workflows/test.yml
- Project.toml
- src/CxxWrap.jl
This should make it less painful to develop CxxWrap-based packages with Revise activated.
> Improve revise compatibility

- src/StdLib.jl
The Julia stdlib provides the following convert method:
convert(::Type{T}, s::T) where {T<:AbstractString} = s
convert(::Type{T}, s::AbstractString) where {T<:AbstractString} = T(s)::T
Thus it suffices to provide a conversion constructor for StdStringAllocated.
This is better than a convert method, because the latter introduces
invalidations in other packages (specifically in packages which do *not*
use CxxWrap but which are loaded together with CxxWrap into the same
Julia session).
This is progress on issue #278.
> Replace convert method for StdString to avoid invalidations

- src/CxxWrap.jl
... by convenience constructors. Indeed, from the Julia stdlib, we see
the following convert methods, which imply that these constructors
are fully sufficient:
convert(::Type{T}, x::T)      where {T<:Number} = x
convert(::Type{T}, x::Number) where {T<:Number} = T(x)::T
Note that Julia often inserts `convert` calls into code automatically, so not adding the above avoids a numerous method invalidations in *other* packages.
This is progress on issue #278.
> Avoid invalidations by replacing some convert methods by convenience constructors

- README.md
- src/CxxWrap.jl
- test/inheritance.jl
- test/stdlib.jl
- test/types.jl
- Remove methods that allow comparing an object of type `CxxRef{T}` with one of type `T`. Note that other `Ref` types in Julia don't provide such methods either.
- Remove `convert` methods from `SmartPointer` instances to to other types.
In both cases, the goal is to avoid invalidations. To give an idea of how bad the removed methods were, consider the number of invalidations as computed with this snippet in a fresh Julia session:
using SnoopCompileCore
invalidations = @snoopr using CxxWrap;
length(invalidations)
Before this patch, we get 20819 invalidations with Julia 1.8.4, and 13863 with Julia master.
After this patch, this is down to just 2695 in 1.8.4, respectively 1480 in Julia master.
The main issue with this patch is that it may break code relying on these convenience methods. …
> Remove some automatic conversion and comparison

- src/CxxWrap.jl
This is required to make CxxWrap 0.13 compatible with Polymake.jl. Sorry, I thought that it already was but I clearly made a mistake in my testing :-(.
> Fix ambiguity when converting Ration to CxxNumber

- src/CxxWrap.jl
- test/functions.jl
Only one small change is required for to support Val{T} on the Julia side.
See https://github.com/JuliaInterop/libcxxwrap-julia/pull/123.
> Added support for Val{T}

- src/CxxWrap.jl
Whenever the shared module with C++ code changes, this can mean that
functions or types were added/changed/removed. Forgetting to trigger a
precompilation can cause weird bugs during development. So let's just do
this automatically.
> Trigger fresh precompilation when .so changes

- Project.toml
- README.md
- src/CxxWrap.jl
- src/StdLib.jl
- test/basic_types.jl
- test/containers.jl
- test/extended_module.jl
- test/functions.jl
- test/hello.jl
- test/inheritance.jl
- test/parametric.jl
- test/pointer_modification.jl
- test/types.jl
This fixes `PackageCompiler` relocatability issues described in #333
> Provide library path to wrapmodule via callback instead of a compile-time constant

- src/StdLib.jl
- test/stdlib.jl
Added the complete test set for the StdDeque and its iterator interface and edited an error I made while resolving a conflict in the last merge
> Added tests, edited errors

- src/StdLib.jl
- test/stdlib.jl
Currently, `std::string`s that have null bytes in them cannot be converted to `String`s without truncation using the StdLib-provided `String` constructor.  `Base.unsafe_string` with one argument assumes the pointed-to string is null-terminated, but `std::string`s are not necessarily null-terminated.  `Base.unsafe_string` supports an optional second argument (thanks @omus for pointing this out!) which is the number of bytes in the pointed-to string; this PR uses `cppsize` to get that.  I've also added some small tests to confirm how null-byte containing strings are handled (from the `String`-to-`std::string` direction and vice-versa); I didn't change the default `StdString` constructor to use the length of the julia `String`, although IMO whether that default should be changed is IMO up …
> use `cppsize` when constructing `String` from `StdString`

- src/CxxWrap.jl
Makes a minor modification to `@cxxdeference` to stop that macro from add in line number information which blocks convenient macros likes `@which` and `@edit` from working properly:
```julia
julia> using CxxWrap
julia> foo() = 1
foo (generic function with 1 method)
julia> @which foo()
foo()
@ Main REPL[2]:1
julia> @cxxdereference foo() = 1
foo (generic function with 1 method)
julia> @which foo()
foo()
@ Main ~/.julia/packages/CxxWrap/VnssN/src/CxxWrap.jl:846
julia> @macroexpand @cxxdereference foo() = 1
:(function foo(; )
#= /Users/cvogt/.julia/packages/CxxWrap/VnssN/src/CxxWrap.jl:846 =#
#= REPL[8]:1 =#
1
end)
```
With this PR:
```julia
julia> using CxxWrap
julia> @cxxdereference foo() = 1
foo (generic function with 1 method)
julia> @which foo()
foo()
@ Main REPL[2]:1
```
> Stop `@cxxdereference` from messing up linenum information

- README.md
- src/StdLib.jl
- test/stdlib.jl
Update `StdString` Julia string interface to handle UTF-8 code points. For example on CxxWrap 0.14:
```julia
julia> using CxxWrap
julia> str = "¿\0ÿ"
"¿\0ÿ"
julia> codeunits(str)
5-element Base.CodeUnits{UInt8, String}:
0xc2
0xbf
0x00
0xc3
0xbf
julia> std_str = StdString(str, ncodeunits(str))
"¿"
julia> collect(std_str)
5-element Vector{Char}:
'Â': Unicode U+00C2 (category Lu: Letter, uppercase)
'¿': Unicode U+00BF (category Po: Punctuation, other)
'\0': ASCII/Unicode U+0000 (category Cc: Other, control)
'Ã': Unicode U+00C3 (category Lu: Letter, uppercase)
'¿': Unicode U+00BF (category Po: Punctuation, other)
julia> codeunits(std_str)
5-element Base.CodeUnits{UInt8, CxxWrap.StdLib.StdStringAllocated}:
0xc2
0xbf
0x00
0xc3
0xbf
julia> String(codeunits(std_str))
"¿\0ÿ"
julia> convert(String, …
```
> Handle UTF-8 code points in `StdString`

- src/StdLib.jl
- test/stdlib.jl
Fixes https://github.com/JuliaInterop/CxxWrap.jl/issues/367. With this PR the `StdVector` constructors now support specifying the element type of the vector. Additionally, I've refactored the code to be more inlined with how `Vector` behaves and have added a more extensive test suite.
Example of the new behaviour of this PR using the examples from #357:
```julia
julia> StdVector{StdString}()
0-element CxxWrap.StdLib.StdVectorAllocated{StdString}
julia> StdVector(StdString[])
0-element CxxWrap.StdLib.StdVectorAllocated{StdString}
julia> StdVector(StdString["hello"])
1-element CxxWrap.StdLib.StdVectorAllocated{StdString}:
"hello"
julia> StdVector{StdString}(StdString["hello"])
1-element CxxWrap.StdLib.StdVectorAllocated{StdString}:
"hello"
```
> Parameterized constructors for `StdVector`

- src/CxxWrap.jl
This seems to be needed for julia nightly, otherwise the CxxWrap tests error with:
```
basic_types: Error During Test at /home/pkgeval/.julia/packages/CxxWrap/66SRr/test/basic_types.jl:186
Test threw exception
Expression: BasicTypes.test_argv(Cint(length(argv)), argv) == join(argv)
type RefArray has no field cpp_object
Stacktrace:
[1] getproperty
@ Base ./Base.jl:37 [inlined]
[2] unsafe_convert(to_type::Type{CxxPtr{CxxPtr{CxxChar}}}, x::Base.RefArray{Ptr{Int8}, Vector{Ptr{Int8}}, Vector{Any}})
@ CxxWrap.CxxWrapCore ~/.julia/packages/CxxWrap/66SRr/src/CxxWrap.jl:271
[3] test_argv(arg1::Int32, arg2::Vector{String})
@ Main.BasicTypes ~/.julia/packages/CxxWrap/66SRr/src/CxxWrap.jl:624
[4] macro expansion
@ /opt/julia/share/julia/stdlib/v1.11/Test/src/Test.jl:676 [inlined]
[5] macro expansion …
```
> convert: add new RefArray type signature

- Project.toml
- src/CxxWrap.jl
- test/basic_types.jl
- test/types.jl
> Properly deal with const template parameters

- .github/workflows/test-linux-mac.yml
- .github/workflows/test-win.yml
- src/StdLib.jl
- test/stdlib.jl
https://github.com/PraneethJain/libcxxwrap-julia
Added StdFill
(Also removed a StdDeque constructor which didn't exist on libcxxwrap side and was thus incorrect)
> Add StdFill

- .github/workflows/test-linux-mac.yml
- .github/workflows/test-win.yml
- src/CxxWrap.jl
- src/StdLib.jl
- test/stdlib.jl
https://github.com/PraneethJain/libcxxwrap-julia#StdMultiset
Add support for `std::set` and `std::multiset`
> StdSet and StdMultiset support

- src/CxxWrap.jl
Resolves https://github.com/JuliaInterop/CxxWrap.jl/issues/425 in the way that is outlined in the docstrings
```julia
help?> Base.promote_type
promote_type(type1, type2, ...)
Promotion refers to converting values of mixed types to a single common type.
promote_type represents the default promotion behavior in Julia when operators (usually
mathematical) are given arguments of differing types. promote_type generally tries to
return a type which can at least approximate most values of either input type without
excessively widening. Some loss is tolerated; for example, promote_type(Int64, Float64)
returns Float64 even though strictly, not all Int64 values can be represented exactly as
Float64 values.
See also: promote, promote_typejoin, promote_rule.
[...]
│ Don't overload this directly
│
│ …
```
> Remove overloading `promote_type`

- Project.toml
- src/CxxWrap.jl
- src/StdLib.jl
- test/stdlib.jl
https://github.com/PraneethJain/libcxxwrap-julia#linear-containers
- The `push!` and `pop!` methods for `StdQueue` now return the container after mutating it. Added missing methods (`length` and `isempty`) for `StdQueue`. Improved the test set.
- Added `StdStack` support
> Add `StdStack` and fix `StdQueue` methods

- README.md
I needed these recently and it took a bit of digging through the code to figure out how to use them.
> Document `DefaultConstructible` and `CopyConstructible`

- README.md
- src/StdLib.jl
- src/StdLib/StdDeque.jl
- src/StdLib/StdForwardList.jl
- src/StdLib/StdList.jl
- src/StdLib/StdMultisetTypes.jl
- src/StdLib/StdSetTypes.jl
https://github.com/JuliaInterop/libcxxwrap-julia#main
- Added a macro to add iterators given a container type and its iterator type
- Mentioned that the STL containers are iterable in the readme.
> refactor: iterators

- test/stdlib.jl
This should avoid intermittent errors like this https://github.com/JuliaInterop/libcxxwrap-julia/actions/runs/12225741316/job/34100102886?pr=177#step:4:1251 in https://github.com/JuliaInterop/libcxxwrap-julia/pull/177.
```julia
3: parameterized constructors: Test Failed at /Users/runner/.julia/packages/CxxWrap/VaRGA/test/stdlib.jl:191
3:   Expression: vec == ["a", "b", "c"]
3:    Evaluated: StdString[":5\xe7}\"\0\0\xc8\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xe015\xe7}\"\0\0\x99", "15\xe7}\"\0\0\x99\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa0=5\xe7}\"\0\0\xde\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x10\x04\f\xe5}\"\0\0\b\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", "=5\xe7}\"\0\0\xde\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x10\x04\f\xe5}\"\0\0\b …
```
> tests: keep some string vectors alive for references

- src/CxxWrap.jl
To fix these warnings (future errors) during precompilation on julia nightly:
```
┌ CxxWrap
│  WARNING: Detected access to binding `StdLib.__cxxwrap_pointers` in a world prior to its definition world.
│    Julia 1.12 has introduced more strict world age semantics for global bindings.
│    !!! This code may malfunction under Revise.
│    !!! This code will error in future versions of Julia.
│  Hint: Add an appropriate `invokelatest` around the access to this binding.
│  WARNING: Detected access to binding `StdLib.__cxxwrap_methodkeys` in a world prior to its definition world.
│    Julia 1.12 has introduced more strict world age semantics for global bindings.
│    !!! This code may malfunction under Revise.
│    !!! This code will error in future versions of Julia.
│  Hint: Add an …
```
> use invokelatest to access bindings generated with Core.eval
