deps/build.jl

I'm on Fedora24, getting julia from the COPR repos.
My libjulia is /usr/lib64/libjulia.so

Updating build file for Fedora 24

---

deps/build.jl
deps/src/cxx_wrap/CMakeLists.txt
deps/src/cxx_wrap/FindJulia.cmake

This should allow the removal of some code from `build.jl` and also enable the use of CxxWrap in a standalone fashion.

Use a FindJulia.cmake script instead of hardcoded directories

---

README.md
deps/src/jlcxx/include/jlcxx/type_conversion.hpp

Redme fixes and cpp fixup for build agains Julia 0.4

---

.travis.yml
deps/src/jlcxx/include/jlcxx/jlcxx.hpp

@barche everything is back to green!!!

Fixup allow-failures

---

README.md

The links on the README.md are broken for some of the .cpp files.

Fix Links on Readme

---

README.md

Link to Cxx.jl

---

deps/build.jl

Built and tested, it works for me. Use build CxxWrap, test CxxWrap
resolves issue #116

Quick fix for julia-1.0.1 build. 

---

src/CxxWrap.jl
test/pointer_modification.jl
test/types.jl

Add unique keys for methods

---

.travis.yml
appveyor.yml
src/CxxWrap.jl
test/basic_types.jl

Add conversion for Bool

---

src/CxxWrap.jl
test/basic_types.jl

Rework integer type definition

---

src/CxxWrap.jl
test/basic_types.jl

Issue #242
Before:
```julia
julia> @time using CxxWrap
10.261479 seconds (23.77 M allocations: 1.168 GiB, 2.19% gc time)
```
After:
```julia
julia> @time using CxxWrap
1.855931 seconds (3.14 M allocations: 168.659 MiB, 0.40% gc time)
```

Speed up package loading time

---

src/CxxWrap.jl

... and if not produce a human readable error.
Related to issue #246 in that it would have given a slightly more helpful error message there.

Check whether libcxxwrap_julia_jll works

---

README.md

See https://github.com/JuliaInterop/libcxxwrap-julia/pull/55

README.md: mention that a C++17 compiler is required

---

src/CxxWrap.jl
test/parametric.jl

Fix errors in the cxxdereference macro

---

src/CxxWrap.jl

Issue #258
Seems the conversion is not needed at all.

Remove convert to any

---

src/CxxWrap.jl
test/functions.jl

See issue https://github.com/barche/QML.jl/issues/102#issuecomment-761591430

Allow SafeCFunction to work on a closure

---

README.md

[readme] update JuliaCon links to youtube

---

src/CxxWrap.jl

... to make it a bit clearer in some cases what really is going on.

Rewrite type parameters of `Base.convert` methods

---

src/CxxWrap.jl

Part of PR #335 which should be 100% transparent. I figured it might be good to get this merged first, while I fix the other PR, as it makes it clearer what that PR actually changes

Use CxxNumber some more to make code more readable

---

Project.toml
README.md
src/CxxWrap.jl
test/pointer_modification.jl
test/types.jl

@fingolfin This contains one extra promote_rule to fix an error with enums in QML.jl, I assume this has no effect on invalidations?

Convert fixes and new version

---

src/StdLib.jl

Add method to Base.between to fix string indexing

---

.github/workflows/test-linux-mac.yml
.github/workflows/test-win.yml
.github/workflows/test.yml
src/CxxWrap.jl
src/StdLib.jl
test/stdlib.jl

https://github.com/PraneethJain/libcxxwrap-julia
queue

feat: add basic queue support

---

.github/workflows/test-linux-mac.yml
.github/workflows/test-win.yml

https://github.com/JuliaInterop/libcxxwrap-julia/#main

feat: change PR body format

---

README.md

Document memory management for return values

---

README.md
src/CxxWrap.jl
test/inheritance.jl

https://github.com/JuliaInterop/libcxxwrap-julia#main

Add support for dynamic casting on the Julia side

---

src/CxxWrap.jl
src/StdLib.jl
test/stdlib.jl

https://github.com/PraneethJain/libcxxwrap-julia#priority-queue
Add `StdPriorityQueue` and its tests

feat: StdPriorityQueue

---

src/CxxWrap.jl
src/StdLib.jl
test/stdlib.jl

https://github.com/PraneethJain/libcxxwrap-julia#lists
Added STL list types

feat: add StdList and StdForwardList

---

README.md

- Added a table documenting containers and the versions of the library they are available for
- Linked the `StdLib` directory to check available methods for each container

doc: STL containers

---

src/CxxWrap.jl
src/StdLib.jl
src/StdLib/StdList.jl
test/stdlib.jl

https://github.com/PraneethJain/libcxxwrap-julia#stl-algos
Refer to https://github.com/JuliaInterop/libcxxwrap-julia/pull/171 for description

Add support for common STL algorithms

---

.github/workflows/test-linux-mac.yml
.github/workflows/test-win.yml
test/containers.jl
test/stdlib.jl

https://github.com/JuliaInterop/libcxxwrap-julia#fix-array

Add test for jlcxx::Array<int>

---

src/CxxWrap.jl
src/StdLib/StdVector.jl
test/containers.jl

https://github.com/JuliaInterop/libcxxwrap-julia#tuple-fixes

Improve support for Tuples

---

test/inheritance.jl

https://github.com/JuliaInterop/libcxxwrap-julia#inheritance
Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/10818

Add extra inheritance example

---

.github/workflows/test-linux-mac.yml
Project.toml
README.md
src/CxxWrap.jl

Check type definition in current world age
